### Create Report:
POST http://localhost:4000/user/register
Content-Type: application/json

{
    "email": "whatever@gmail.com",
    "username": "what",
    "password": "evAAer_1"
}

### Get a specific user by id
GET http://localhost:4000/user/1

### Get users with specific username
GET http://localhost:4000/user?username=what

### Get users with specific email
GET http://localhost:4000/user?email=whatever@gmail.com


### Update a user
PATCH http://localhost:4000/user/2
Content-Type: application/json

{
    "password": "This_x_WHatevr3"
}

### Update a user, multiple changes:
PATCH http://localhost:4000/user/4
Content-Type: application/json

{
    "email": "another@gmail.com",
    "username": "whatever"
}

### Delete a user
DELETE http://localhost:4000/user/6