### Get the status of this man
GET http://localhost:4000


### Do some exercise
POST http://localhost:4000/exercise
Content-Type: application/json

{
    "minutes": 500
}


### Listen to music a little
POST http://localhost:4000/music
Content-Type: application/json

{
    "minutes": 300
}